[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"

[workspace.lints.clippy]
result_large_err = "allow"

[workspace.dependencies]
forge-core = { path = "crates/forge-core" }
forge-diagnostics = { path = "crates/forge-diagnostics" }
forge-engine = { path = "crates/forge-engine" }
forge-script = { path = "crates/forge-script" }

blake3 = { version = "1", features = ["rayon"] }
parking_lot = "0.12"
petgraph = "0.8"
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
toml_edit = "0.25"
rhai = "1"
clap = { version = "4", features = ["derive"] }
rayon = "1"
rusqlite = { version = "0.40", features = ["bundled"] }
ureq = "3"
walkdir = "2"
tar = "0.4"
flate2 = "1"
xz2 = { version = "0.1", features = ["static"] }
sha2 = "0.11"
notify = "8"
regex = "1"
ignore = "0.4"

[profile.release]
lto = true
strip = true
