[library.forge_core]
srcs = ["${glob('crates/forge-core/src/**/*.rs')}"]
deps = ["forge_diagnostics"]

[library.forge_diagnostics]
srcs = ["${glob('crates/forge-diagnostics/src/**/*.rs')}"]

[library.forge_engine]
srcs = ["${glob('crates/forge-engine/src/**/*.rs')}"]
hdrs = ["${glob('crates/forge-engine/migrations/**/*')}"]
deps = ["forge_core", "forge_diagnostics", "forge_script"]

[library.forge_script]
srcs = ["${glob('crates/forge-script/src/**/*.rs')}"]
hdrs = ["${glob('prelude/**/*')}"]
deps = ["forge_core", "forge_diagnostics"]

[binary.forge]
srcs = ["${glob('crates/forge/src/**/*.rs')}"]
deps = ["forge_core", "forge_diagnostics", "forge_engine", "forge_script"]
