[cells.c]
scripts = ["c/cell.rhai"]
extensions = ["c", "h", "cpp", "cc", "cxx", "C", "hpp", "hh", "hxx", "cppm", "ixx", "mpp", "cxxm"]
preferred_toolchain = "clang"
fallback_toolchains = ["gcc", "cc"]

[cells.rust]
scripts = ["rust/workspace.rhai", "rust/manifest.rhai", "rust/cfg.rhai", "rust/features.rhai", "rust/build_script.rhai", "rust/cell.rhai"]
workspace_script = "rust/workspace.rhai"
extensions = ["rs"]
preferred_toolchain = "rust"
fallback_toolchains = ["rustc"]
standard = "2024"
