[package]
name = "forge"
description = "A hermetic, content-addressed build system"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "forge"
path = "src/main.rs"

[dependencies]
forge-core.workspace = true
forge-diagnostics.workspace = true
forge-engine.workspace = true
forge-script.workspace = true

clap.workspace = true
notify.workspace = true
ignore.workspace = true
miette.workspace = true
serde_json.workspace = true
blake3 = { workspace = true, features = ["rayon"] }

[lints]
workspace = true

[dev-dependencies]
rusqlite.workspace = true
