#include <stdio.h>

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <output_file>\n", argv[0]);
        return 1;
    }
    
    FILE* f = fopen(argv[1], "w");
    if (!f) {
        fprintf(stderr, "Could not open %s for writing\n", argv[1]);
        return 1;
    }
    
    fprintf(f, "// Generated by codegen host tool\n");
    fprintf(f, "int get_magic_number() { return 42; }\n");
    fclose(f);
    
    printf("Successfully generated %s\n", argv[1]);
    return 0;
}
