#include <stdio.h>

// Forward declaration for function generated by codegen.c
extern int get_magic_number();

int main() {
    printf("The magic number generated by the host tool is: %d\n", get_magic_number());
    return 0;
}
